import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { fileURLToPath } from "url";
import { dirname } from "path";

const __dirname = dirname(fileURLToPath(
	import.meta.url));

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

/**
 * Stub plugin for native Node.js addons (.node files).
 *
 * ssh2 (a dependency of ssh2-sftp-client) ships a native crypto accelerator
 * but falls back gracefully to pure-JS crypto when the native binding is
 * unavailable.  Since esbuild cannot bundle .node binaries, we intercept
 * any require() for them and return a module that throws when it is
 * required, exactly like a missing binary would.
 *
 * It must throw at require time, not at call time: ssh2 picks its
 * implementation with `try { binding = require('…/sshcrypto.node') } catch {}`
 * and then uses the native classes whenever `binding` is set. A stub that
 * loads successfully (e.g. a Proxy whose properties throw when called) makes
 * ssh2 choose the native path, and every connection then fails on its first
 * encrypted packet with "Native module not available … AESGCMDecipher" (or
 * GenericDecipher, ChaChaPolyDecipher, depending on the negotiated cipher).
 * cpu-features is required the same way inside a try, so it falls back too.
 */
const nativeNodeModulesPlugin = {
	name: 'native-node-modules',
	setup(build) {
		// Intercept .node file imports and mark them as the special namespace
		build.onResolve({ filter: /\.node$/ }, args => ({
			path: args.path,
			namespace: 'node-native-stub',
		}));
		// Throw on require, so callers' try/catch selects their pure-JS fallback
		build.onLoad({ filter: /.*/, namespace: 'node-native-stub' }, args => ({
			contents: `throw new Error(${JSON.stringify('[Folder Bridge] Native module not available in bundled context: ' + args.path)});\n`,
			loader: 'js',
		}));
	},
};

const optionalNodeModulesPlugin = {
	name: 'optional-node-modules',
	setup(build) {
		build.onResolve({ filter: /^\.\/optionalNodeModules$/ }, args => {
			if (!args.importer.replace(/\\/g, '/').endsWith('/src/runtimeNode.ts')) {
				return null;
			}

			return {
				path: 'folderbridge-optional-node-modules',
				namespace: 'folderbridge-optional-node-modules',
			};
		});

		build.onLoad({ filter: /.*/, namespace: 'folderbridge-optional-node-modules' }, () => ({
			contents: `
export function loadBundledOptionalModule(moduleId) {
	try {
		switch (moduleId) {
			case 'chokidar':
				return require('chokidar');
			case '@aws-sdk/client-s3':
				return require('@aws-sdk/client-s3');
			case 'ssh2-sftp-client':
				return require('ssh2-sftp-client');
			case 'webdav':
				return require('webdav');
			default:
				return null;
		}
	} catch {
		return null;
	}
}
`,
			loader: 'js',
			resolveDir: __dirname,
		}));
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	platform: 'node',
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins
	],
	plugins: [nativeNodeModulesPlugin, optionalNodeModulesPlugin],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: process.env.FOLDERBRIDGE_BUILD_OUTFILE || 'main.js',
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
